name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -G "Xcode" -DCMAKE_CONFIGURATION_TYPES=Release
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -v -- -verbose
    - name: list
      run: cmake --build build --config Release --target ALL_BUILD -v -- -list
    - name: Manual ctest
      run: cd build && ctest -C Release --verbose --extra-verbose --output-on-failure
    - name: Test
      run: CTEST_OUTPUT_ON_FAILURE=1 VERBOSE=1 cmake --build build --config Release --target RUN_TESTS -v -- -verbose
    - name: Install
      run: cmake --build build --config Release --target install -v
  make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v
